src/Entity/Stars.php
<?php

namespace App\Entity;

use App\Repository\StarsRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

#[ORM\Entity(repositoryClass: StarsRepository::class)]
class Stars
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'id', nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?int $constellation_id = null;

    #[ORM\ManyToOne(targetEntity: Constellations::class, inversedBy: 'stars')]
    #[ORM\JoinColumn(name: 'constellation_id', referencedColumnName: 'id', nullable: true)]
    private ?Constellations $constellation = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $x_position = null;

    #[ORM\Column]
    private ?float $y_position = null;

    #[ORM\Column]
    private ?float $z_position = null;

    #[ORM\Column]
    private ?float $brightness = null;

    #[ORM\Column(length: 20)]
    private ?string $color = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 300)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $size = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $event_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $modelPath = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageUrl = null;


    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }


    public function getConstellationId(): ?int
    {
        return $this->constellation_id;
    }

    public function setConstellationId(int $constellation_id): static
    {
        $this->constellation_id = $constellation_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getXPosition(): ?float
    {
        return $this->x_position;
    }

    public function setXPosition(float $x_position): static
    {
        $this->x_position = $x_position;

        return $this;
    }

    public function getYPosition(): ?float
    {
        return $this->y_position;
    }

    public function setYPosition(float $y_position): static
    {
        $this->y_position = $y_position;

        return $this;
    }

    public function getZPosition(): ?float
    {
        return $this->z_position;
    }

    public function setZPosition(float $z_position): static
    {
        $this->z_position = $z_position;

        return $this;
    }

    public function getBrightness(): ?float
    {
        return $this->brightness;
    }

    public function setBrightness(float $brightness): static
    {
        $this->brightness = $brightness;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): static
    {
        $this->color = $color;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): static
    {
        $this->size = $size;

        return $this;
    }

    public function getEventDate(): ?\DateTimeImmutable
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeImmutable $event_date): static
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getModelPath(): ?string
    {
        return $this->modelPath;
    }

    public function setModelPath(string $modelPath): static
    {
        $this->modelPath = $modelPath;
        return $this;
    }

    public function __toString(): string
    {
        return $this->name ?? 'Unnamed Star'; // Retourne le nom de l'étoile
    }

    public function getStarProperties(): array
    {
        return [
            'name' => $this->name,
            'description' => $this->description,
            'size' => $this->size,
            'color' => $this->color,
            'brightness' => $this->brightness,
            'event_date' => $this->event_date->format('Y-m-d'),
            'x_position' => $this->x_position,
            'y_position' => $this->y_position,
            'modelPath' => $this->modelPath,
        ];
    }

    public function getConstellation(): ?Constellations
    {
        return $this->constellation;
    }

    public function setConstellation(?Constellations $constellation): self
    {
        $this->constellation = $constellation;
        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(?string $imageUrl): self
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }
}

src/Form/StarsType.php
<?php

namespace App\Form;

use App\Entity\Stars;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ColorType;

class StarsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('size')
            ->add('event_date', null, [
                'widget' => 'single_text',
            ])
            ->add('x_position')
            ->add('y_position')
            ->add('brightness')
            ->add('color', ColorType::class, [
                'label' => 'Couleur de l\'étoile',
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stars::class,
        ]);
    }
}

src/Controller/StarsController.php
<?php

namespace App\Controller;

use App\Entity\Stars;
use App\Form\StarsType;
use App\Repository\StarsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\SecurityBundle\Security;

#[IsGranted('IS_AUTHENTICATED_FULLY')] #  restriction pour que seuls les utilisateurs connectés puissent accéder aux pages du CRUD.
#[Route('/stars')]
final class StarsController extends AbstractController
{
    #[Route(name: 'app_user_stars', methods: ['GET'])]
    public function index(StarsRepository $starsRepository): Response
    {
        $user = $this->getUser();
        return $this->render('stars/index.html.twig', [
            'stars' => $starsRepository->findBy(['user' => $user]),
        ]);
    }

    #[Route('/new', name: 'app_stars_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $star = new Stars();
        $form = $this->createForm(StarsType::class, $star);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $star->setUser($this->getUser());  // Associer l'utilisateur connecté

            $entityManager->persist($star);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_stars', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stars/new.html.twig', [
            'star' => $star,
            'form' => $form,
        ]);
    }

    #[Route('/get-star/{id}', name: 'get_star', methods: ['GET'])]
    public function getStar(Stars $star): JsonResponse
    {
        return new JsonResponse($star->getStarProperties());
    }


    #[Route('/{id}', name: 'app_stars_show', methods: ['GET'])]
    public function show(Stars $star): Response
    {
        return $this->render('stars/show.html.twig', [
            'star' => $star,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_stars_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Stars $star, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StarsType::class, $star);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_user_stars', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('stars/edit.html.twig', [
            'star' => $star,
            'form' => $form,
        ]);
    }

    #[Route('/save-image/{id}', name: 'save_image', methods: ['POST'])]
    public function saveImage(int $id, Request $request, EntityManagerInterface $entityManager, StarsRepository $starsRepository): JsonResponse
    {
        // Récupérer les données de la requête
        $data = json_decode($request->getContent(), true);

        // Vérifier si l'image est présente dans les données
        if (!isset($data['image'])) {
            return new JsonResponse(['error' => 'Image manquante'], Response::HTTP_BAD_REQUEST);
        }

        $imageData = $data['image'];  // récupère l'image depuis les données

        // Traitement de l'image
        $base64 = str_replace('data:image/png;base64,', '', $imageData);
        $decodedImage = base64_decode($base64);

        if ($decodedImage === false) {
            return new JsonResponse(['error' => 'Erreur lors du décodage de l\'image'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        // Sauvegarde de l'image 
        $fileName = 'star_' . $id . '.png';
        $filePath = 'uploads/images/' . $fileName;
        
        if (file_put_contents($filePath, $decodedImage) === false) {
            return new JsonResponse(['error' => 'Échec de l\'enregistrement de l\'image'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }

        // Mettre à jour l'entité avec le chemin de l'image
        $star = $starsRepository->find($id);
        $star->setImageUrl($filePath);
        $entityManager->flush();

        // Retourner une réponse JSON avec le chemin de l'image
        return new JsonResponse([
            'message' => 'Image enregistrée avec succès',
            'path' => $filePath
        ]);
    }

    #[Route('/{id}', name: 'app_stars_delete', methods: ['POST'])]
    public function delete(Request $request, Stars $star, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $star->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($star);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_stars_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/stars/_delete_form.html.twig
<form method="post" action="{{ path('app_stars_delete', {'id': star.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ star.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/stars/_form.html.twig
{% block body %}
<div class="container">
	<div class="main">
		{{ form_start(form, {'attr': {'class': 'form-container2'}}) }}
		<!-- Colonne gauche -->
        <div class="form-grid">
            <div>
                <div class="form-group2">
                    {{ form_label(form.name, 'Nom') }}
                    {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder': 'Entrez le nom de votre étoile'}}) }}
                </div>
                <div class="form-group2">
                    {{ form_label(form.description, 'Description') }}
                    {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder': 'Décrivez l\'évènement associé à votre étoile'}}) }}
                </div>
                <div class="form-group2">
                    {{ form_label(form.event_date, 'Date de l\'évènement') }}
                    {{ form_widget(form.event_date, {'attr': {'class': 'form-control', 'placeholder': 'Date de l\'évènement associé à votre étoile'}}) }}
                </div>
            </div>
            <!-- Colonne droite -->
            <div>
                <div class="form-group2">
                    {{ form_label(form.color, 'Couleur') }}
                    {{ form_widget(form.color, {'attr': {'id':'starColor','class': 'form-control', 'type': 'color', 'placeholder': 'Choisissez la couleur de votre étoile'}}) }}
                </div>
                <div class="form-group2">
                    {{ form_label(form.size, 'Taille') }}
                    {{ form_widget(form.size, {'attr': {'id':'starSize','class': 'form-control', 'type': 'number', 'placeholder': 'Choisissez la taille de votre étoile'}}) }}
                </div>

                <div class="form-group2">
                    {{ form_label(form.brightness, 'Brillance') }}
                    {{ form_widget(form.brightness, {'attr': {'class': 'form-control', 'type': 'number', 'placeholder': 'Choisissez la brillance de votre étoile'}}) }}
                </div>

                <div class="form-group2">
                    {{ form_label(form.x_position, 'Position X') }}
                    {{ form_widget(form.x_position, {'attr': {'class': 'form-control', 'type': 'number', 'placeholder': 'Choisissez la position de votre étoile en X'}}) }}
                </div>

                <div class="form-group2">
                    {{ form_label(form.y_position, 'Position Y') }}
                    {{ form_widget(form.y_position, {'attr': {'class': 'form-control', 'type': 'number', 'placeholder': 'Choisissez la position de votre étoile en Y'}}) }}
                </div>
            </div>

            <div class="form-footer">
                <button type="submit">{{ button_label|default('Créer mon étoile') }}</button>
            </div>
           
        </div>
        <!-- Conteneur pour la vue 3D -->
        <div id="threejs-container" data-star-id="{{ star.id }}"></div>

    {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/stars/edit.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Modifier Stars{% endblock %}

{% block body %}
    <h1>Modifier Stars</h1>
    <br>
    <p><a href="{{ path('app_user_stars') }}" class="lienBtn">Retour</a></p>

    {{ include('stars/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    
    <div class="form-footer">
        {{ include('stars/_delete_form.html.twig') }}
    </div>

{% endblock %}

templates/stars/index.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Mes Stars
{% endblock %}

{% block body %}
	<h1>Mes Stars</h1>
    <br>
	<a href="{{ path('app_stars_new') }}" class="lienBtnCreate">Créer ma star</a>

	<div class="post-container">
		{% for star in stars %}
			<div
				class="post">
				<!-- En-tête avec profil utilisateur -->
				<div class="post-header">
					<span class="username">{{ star.name  }}</span>
				</div>

				<!-- Image du partage -->
				<div class="post-image">
					<img src="{{ star.imageUrl }}" alt="Image du partage">
				</div>

				<div class="post-footer">
					<p class="description">Description : {{ star.description }}</p>
					<br>
					<p>
						Créer le :
                        {{ star.createdAt ? star.createdAt|date('Y-m-d H:i:s') : '' }}</td>

                        </p>
					<p>
						<a href="{{ path('app_stars_edit', {'id': star.id}) }}">Modifier</a>
						<a href="{{ path('app_stars_delete', {'id': star.id}) }}">Supprimer</a>
					</p>
				</div>
			</div>
		{% else %}
			<p>Aucun partage à afficher.</p>
		{% endfor %}
	</div>

{% endblock %}

templates/stars/new.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block body %}
    <p><a href="{{ path('app_user_stars') }}" class="lienBtn">Retour</a></p>
    {{ include('stars/_form.html.twig') }}
{% endblock %}

templates/stars/show.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}Stars{% endblock %}

{% block body %}
    <h1>Stars</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ star.id }}</td>
            </tr>
            <tr>
                <th>Constellation_id</th>
                <td>{{ star.constellationId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ star.name }}</td>
            </tr>
            <tr>
                <th>X_position</th>
                <td>{{ star.xPosition }}</td>
            </tr>
            <tr>
                <th>Y_position</th>
                <td>{{ star.yPosition }}</td>
            </tr>
            <tr>
                <th>Brightness</th>
                <td>{{ star.brightness }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ star.color }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ star.createdAt ? star.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ star.updatedAt ? star.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_stars') }}" class="lienBtnCreate">Retour</a>

    <a href="{{ path('app_stars_edit', {'id': star.id}) }}" class="lienBtn">Modifier</a>
    {{ include('stars/_delete_form.html.twig') }}
{% endblock %}